name: "[BOT] Update README with Go"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        
      - name: Initialize Go module
        run: go mod init github.com/di4m0nds/di4m0nds
        
      - name: Build and run Go app
        run: go run .

      - name: Commit and push if changed
        run: |
          git config --local user.email "ws.2000.sja@gmail.com"
          git config --local user.name "di4m0nds"
          git add README.md
          # git diff --quiet && git diff --staged --quiet || git commit -m "[BOT] Update README with latest articles" && git push origin main
          git commit -m "[BOT] Update README with latest articles" && git push origin main
